// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/regalos/[...category]": InferRoute<import("./src/app/regalos/[...category]/routeType").RouteType>;
  }

  interface StaticRouter {
    "/account/login": StaticRoute;
    "/account/recoveryPassword": StaticRoute;
    "/account/register": StaticRoute;
    "/myorder/cesta": StaticRoute;
    "/myorder/checkout": StaticRoute;
    "/myorder/information": StaticRoute;
    "/": StaticRoute;
    "/regalos": StaticRoute;
  }
}
