services:
    lazo:
        image: lazo-frontend
        container_name: lazo-frontend
        restart: always
        build:
            context: ./
        working_dir: /app
        ports:
            - '3011:3000'
        networks:
            - network-lazo
        tty: true

networks:
    network-lazo:
        driver: bridge
        external: true
