services:
    lazo:
        container_name: lazo-frontend
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        working_dir: /app
        command: sh -c "yarn install && yarn dev"
        ports:
            - 3011:3000
        volumes:
            - .:/app
        networks:
            - network-lazo

networks:
    network-lazo:
        driver: bridge
        external: true
